package model

var (
	AllSQLKeywords = []string{
		"SELECT", "FROM", "WHERE", "GROUP BY", "HAVING", "ORDER BY", "LIMIT",
		"DISTINCT", "IN", "LIKE", "BETWEEN", "EXISTS", "JOIN", "INNER JOIN",
		"LEFT JOIN", "RIGHT JOIN", "FULL JOIN", "ON",

		"AND", "OR", "NOT", "IS NULL", "IS NOT NULL", "ANY", "ALL", "BETWEEN", "IN", "LIKE", "IF", "MATCH",

		"CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME",
		"COMMENT", "GRANT", "REVOKE", "SHOW", "DESCRIBE",

		"COMMIT", "ROLLBACK", "SAVEPOINT", "SET TRANSACTION", "BEGIN TRANSACTION",

		"GRANT", "REVOKE",

		"COUNT()", "SUM()", "AVG()", "MIN()", "MAX()",
		"CONCAT()", "LENGTH()", "LOWER()", "UPPER()", "SUBSTRING()",
		"ABS()", "ROUND()", "CEIL()", "FLOOR()", "POWER()", "MOD()",
		"NOW()", "CURDATE()", "DATE_ADD()", "DATE_SUB()", "YEAR()", "MONTH()", "DAY()", "HOUR()", "MINUTE()",
		"INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN", "CROSS JOIN", "SELF JOIN",
		"EXISTS", "IN", "ANY", "ALL", "SELECT", "FROM", "WHERE",
		"CREATE INDEX", "DROP INDEX", "ALTER INDEX",
		"PRIMARY KEY", "FOREIGN KEY", "UNIQUE", "NOT NULL", "CHECK", "DEFAULT",
		"CREATE VIEW", "DROP VIEW", "ALTER VIEW", "CREATE VIRTUAL VIEW",
		"CREATE PROCEDURE", "CREATE FUNCTION", "DROP PROCEDURE", "DROP FUNCTION", "CALL",
		"CREATE TRIGGER", "DROP TRIGGER",
		"CREATE TABLESPACE", "DROP TABLESPACE",
		"CREATE USER", "DROP USER", "ALTER USER", "REVOKE", "GRANT",
	}
)
